### ISSUE TITLE
App generation error

### ISSUE THREAD

**Issue by gEndelf** [jetbase-io/jetbase-generator#1]
During app generation exception was raised.

**Initial data:**

```
? What is the base name of your application? v1
? Which port would like your server to run? It should be unique to avoid port conflicts. 9999
? Which backend do you want to use? Ruby on Rails + PostgreSQL
? Which framework would you like to use for the client? React
```

**Error:**

```
Unable to find client/package.json or missing required pattern. File rewrite failed.
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

Unable to find client/package-lock.json or missing required pattern. File rewrite failed.
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1159:14)
    at Object.createContent (/Users/bb/prj/jetbase/jetbase-generator/generators/utils.js:14:6)
    at module.exports.createContent (/Users/bb/prj/jetbase/jetbase-generator/generators/generator-base.js:28:11)
    at shelljs.exec (/Users/bb/prj/jetbase/jetbase-generator/generators/client/files.js:19:12)
    at /Users/bb/prj/jetbase/jetbase-generator/node_modules/shelljs/src/exec.js:121:9
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
```

**Comment by gEndelf** [comment]
Not reproduced
